### ISSUE TITLE
vSync

### ISSUE THREAD

**Issue by ryanlinn13** [Linesmerrill/lines-police-server#1]
This is not needed if you have vMenu, the same features are implemented in this resource already.

**Comment by Linesmerrill** [comment]
@ryanlinn13 Thanks! Yeah this is just a public version of our communities gta server. Sweet I’ll take out vsync!

**Comment by ryanlinn13** [comment]
under lines-police-server in resources.  FiveM?  or is that an abandoned project?

**Comment by Linesmerrill** [comment]
@ryanlinn13 yeah sorry got this Project confused with another one. Will be removing vSync in our next patch.

**Comment by ryanlinn13** [comment]
all good bro if I see anything outlandish I will post for you also all those cars that you're streaming the civ replacement cars might really slow your server down we had texture issues with those.  Good luck buddy.

**Comment by Linesmerrill** [comment]
Yeah thanks for the suggestions! As for the car packs, yeah we had to beef up our server with a new processor and 64GB of dedicated ram but while running with around 10 people online we have had almost no major texture losses, but definitely something we are keeping in mind for sure.

**Comment by Linesmerrill** [comment]
Ok that has been removed here: 7715c9a10256f63eae9d750ebcac6d4cc4749d46
